baseURL = "https://uat.npsnt.ru/"

[[menu.main]]
name = "О нас"
url = "/about/"
weight = 2

[[menu.main]]
name = "Контакты"
url = "/contacts/"
weight = 3

[[menu.main]]
name = "Личный кабинет"
url = "/profile/"
weight = 4
